random_key: 42

global:
  objective: reg:squarederror
  learning_rate: 0.01
  max_depth: 6
  min_child_weight: 2
  gamma: 0.1
  reg_lambda: 1.0
  reg_alpha: 0.0
  tree_method: hist
  n_estimators: 5000
  subsample: 0.7
  tree_method: approx



biome_mapping:
  Temperate broadleaf forests: Temperate broadleaf forests
  Temperate conifer forests: Temperate conifer forests
  Temperate grasslands: Temperate grasslands
  Xeric shrublands: Xeric shrublands
  Mediterranean woodlands: Mediterranean woodlands
  Flooded grasslands: Flooded grasslands
  Mangroves: Mangroves
  Tundra: Boreal and Tundra forests
  Boreal forests or taiga: Boreal and Tundra forests
  Tropical grasslands: Tropical
  Tropical coniferous forests: Tropical
  Tropical moist broadleaf forests: Tropical
  Tropical dry broadleaf forests: Tropical

Temperate conifer forests:
  params:
    objective: reg:squarederror
    learning_rate: 0.05
    max_depth: 6
    min_child_weight: 5
    gamma: 0.1
    reg_lambda: 2.0
    reg_alpha: 0.5
    tree_method: approx
    n_estimators: 300
    subsample: 0.7

  early_stopping_rounds: 20
  description: Default configuration

Boreal and Tundra forests:
  params:
    objective: reg:squarederror
    learning_rate: 0.02
    max_depth: 6
    min_child_weight: 5
    gamma: 0.1
    reg_lambda: 1.0
    reg_alpha: 0.5
    tree_method: approx
    n_estimators: 90
    subsample: 0.7
  early_stopping_rounds: 10
  description: Regularized for small dataset

Xeric shrublands:
  params:
    objective: reg:squarederror
    learning_rate: 0.01
    max_depth: 6
    min_child_weight: 5
    gamma: 0.1
    reg_lambda: 1.0
    reg_alpha: 0.5
    tree_method: approx
    n_estimators: 200
  early_stopping_rounds: 10
  description: Regularized for small dataset

Temperate grasslands:
  params:
    objective: reg:squarederror
    learning_rate: 0.01
    max_depth: 6
    min_child_weight: 5
    gamma: 0.1
    reg_lambda: 1.0
    reg_alpha: 0.5
    tree_method: approx
    n_estimators: 250
    subsample: 0.7
  early_stopping_rounds: 15
  description: Regularized with more rounds

Mediterranean woodlands:
  params:
    objective: reg:squarederror
    learning_rate: 0.005
    max_depth: 6
    min_child_weight: 5
    gamma: 0.1
    reg_lambda: 2.0
    reg_alpha: 0.5
    tree_method: approx
    n_estimators: 150
    subsample: 0.7
  early_stopping_rounds: 10
  description: Regularized for small dataset (RF better)

Temperate broadleaf forests:
  params:
    objective: reg:squarederror
    learning_rate: 0.01
    max_depth: 6
    min_child_weight: 5
    gamma: 0.1
    reg_lambda: 3.0
    reg_alpha: 0.5
    tree_method: approx
    n_estimators: 380
    subsample: 0.7
  early_stopping_rounds: 5
  description: NA

Tropical:
  params:
    objective: reg:squarederror
    learning_rate: 0.01
    max_depth: 6
    min_child_weight: 5
    gamma: 0.1
    reg_lambda: 2.0
    reg_alpha: 0.5
    tree_method: approx
    n_estimators: 330
    subsample: 0.7
  early_stopping_rounds: 30
  description: Large dataset - more rounds